import uuid
import random
import time
import logging
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from app.models.run import InferenceRun, InputType, RunStatus
from app.schemas.inference import InferenceRequest
from typing import Optional

logger = logging.getLogger(__name__)


class InferenceService:
    """Service for handling inference operations."""
    
    @staticmethod
    def simulate_inference(model: str, input_type: InputType, text: Optional[str]) -> dict:
        """Simulate model inference with realistic mock data."""
        start_time = time.time()
        
        # Simulate processing time (100-2000ms)
        latency_ms = random.randint(100, 2000)
        
        # Generate mock response based on input type
        if input_type == InputType.TEXT:
            output_text = f"Simulated response for text input: {text or 'empty'} using {model}"
            token_count_input = len(text.split()) if text else 10
            token_count_output = random.randint(50, 200)
        elif input_type == InputType.IMAGE:
            output_text = f"Image analysis result generated by {model}. The image contains various visual elements."
            token_count_input = 10
            token_count_output = random.randint(100, 300)
        else:  # MULTIMODAL
            output_text = f"Multimodal analysis combining text and image using {model}. {text or ''}"
            token_count_input = (len(text.split()) if text else 10) + 50
            token_count_output = random.randint(150, 400)
        
        # Calculate cost (mock pricing: $0.001 per 1K tokens)
        total_tokens = token_count_input + token_count_output
        cost_usd = (total_tokens / 1000) * 0.001
        
        return {
            "output_text": output_text,
            "latency_ms": latency_ms,
            "token_count_input": token_count_input,
            "token_count_output": token_count_output,
            "cost_usd": cost_usd
        }
    
    @staticmethod
    async def create_inference_run(
        db: AsyncSession,
        request: InferenceRequest,
        trace_id: Optional[str] = None,
        organization_id: Optional[uuid.UUID] = None,
    ) -> InferenceRun:
        """Create and persist a new inference run."""
        # Simulate inference
        result = InferenceService.simulate_inference(
            request.model,
            request.input_type,
            request.text
        )
        
        # Create run record
        run = InferenceRun(
            id=uuid.uuid4(),
            model_name=request.model,
            input_type=request.input_type,
            input_text=request.text,
            input_image_url=request.image_url,
            output_text=result["output_text"],
            latency_ms=result["latency_ms"],
            token_count_input=result["token_count_input"],
            token_count_output=result["token_count_output"],
            cost_usd=result["cost_usd"],
            trace_id=trace_id,
            organization_id=organization_id,
            status=RunStatus.PENDING
        )
        
        db.add(run)
        await db.commit()
        await db.refresh(run)
        
        logger.info(f"Created inference run {run.id} for model {request.model}")
        return run
    
    @staticmethod
    async def get_run(db: AsyncSession, run_id: uuid.UUID) -> Optional[InferenceRun]:
        """Get a run by ID."""
        result = await db.execute(select(InferenceRun).where(InferenceRun.id == run_id))
        return result.scalar_one_or_none()
    
    @staticmethod
    async def list_runs(
        db: AsyncSession,
        model: Optional[str] = None,
        input_type: Optional[InputType] = None,
        status: Optional[RunStatus] = None,
        min_hallucination: Optional[float] = None,
        limit: int = 100,
        offset: int = 0
    ) -> list[InferenceRun]:
        """List runs with optional filters."""
        query = select(InferenceRun)
        
        if model:
            query = query.where(InferenceRun.model_name == model)
        if input_type:
            query = query.where(InferenceRun.input_type == input_type)
        if status:
            query = query.where(InferenceRun.status == status)
        if min_hallucination is not None:
            query = query.where(InferenceRun.hallucination_score >= min_hallucination)
        
        query = query.order_by(InferenceRun.created_at.desc()).limit(limit).offset(offset)
        
        result = await db.execute(query)
        return result.scalars().all()
