[locust]
host = http://localhost:8000
users = 100
spawn-rate = 10
run-time = 5m
headless = true
html = locust-report.html
csv = locust-stats
loglevel = INFO
master = false
expect-workers = 0
master-bind-host = *
master-bind-port = 5557
